name: Test my custom GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: use custom Action
        uses: NazirAhmd/TEST-GITHUB-ACTION@v2
        with:
          appId: '29b335c9-08a9-4b5a-af0f-15271edddade'
          appSecret: ${{ secrets.TO_ACCESS_AAD_KV }}
          keyVaultName: 'kv-github-action'
          tenantId: 'b1914422-c6d8-4aec-b71b-3aa233f6165e'
          secretName: 'dummy-secret'
          
