name: Test GitHub Action With Federated Credentials

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: '29b335c9-08a9-4b5a-af0f-15271edddade'
          tenant-id: 'b1914422-c6d8-4aec-b71b-3aa233f6165e'
          subscription-id: '519510fb-0bf9-4f36-af25-650e475f54bd' 
          enable-AzPSSession: true
            
      - name: use custom GitHub Action
        uses: NazirAhmd/TEST-GITHUB-ACTION@v3
        with:
          appId: ${{ secrets.GA_AAD_APPID }}
          keyVaultName: 'kv-github-action'
          tenantId: ${{ secrets.GA_TENANTID }}
          secretName: 'dummy-secret'
          
