name: Test my custom GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: use custom Action
        uses: NazirAhmd/TEST-GITHUB-ACTION@v2
        with:
          appId: ${{ secrets.GA_AAD_APPID }}
          appSecret: ${{ secrets.GA_APP_SECRET }}
          keyVaultName: 'kv-github-action'
          tenantId: ${{ secrets.GA_TENANTID }}
          secretName: 'dummy-secret'
          
