name: Test GitHub Action With Federated Credentials

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: '29b335c9-08a9-4b5a-af0f-15271edddade'
          tenant-id: 'b1914422-c6d8-4aec-b71b-3aa233f6165e'
          subscription-id: '519510fb-0bf9-4f36-af25-650e475f54bd' 
          enable-AzPSSession: true
          
      - name: 'Get resource group with PowerShell action'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup
            $secret = Get-AzKeyVaultSecret -VaultName "kv-github-action" -Name "dummy-secret" -AsPlainText
          azPSVersion: "latest"
      
      - name: Retrieve secret from AKV
        uses: azure/CLI@v1
        with:
          inlineScript: |
            secretValue=$(az keyvault secret show --name "dummy-secret" --vault-name "kv-github-action" --query "value")
            echo "SECRETVALUE="$secretValue >> $GITHUB_ENV
            
      - name: use custom Action
        uses: NazirAhmd/TEST-GITHUB-ACTION@v2
        with:
          appId: ${{ secrets.GA_AAD_APPID }}
          appSecret: ${{ secrets.GA_APP_SECRET }}
          keyVaultName: 'kv-github-action'
          tenantId: ${{ secrets.GA_TENANTID }}
          secretName: 'dummy-secret'
          
